[dependencies]
clap = "2.33.3"
serde = "1.0.126"
serde_derive = "1.0.126"
toml = "0.5.8"
itertools = "0.10.1"

[package]
edition = "2018"
name = "cargo-man"
version = "0.0.4"
license = "MIT"
description = "CLI tool to improve Cargo file management."
